name: Publish Package To NPM

on:  
  workflow_run:
    workflows:
      - Node.js CI
    types:
      - completed

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: set node-version
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm packages
        run: npm install

      - name: Unit tests
        run: npm test

      - name: Build Banana
        run: npm run banana -- --build --env prod

      - uses: actions/upload-artifact@v3
        with:
          name: banana
          path: ./build/

      - name: Publish NPM package
        run: npm publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}