name: Publish Package To NPM

on:  
  workflow_run:
    workflows:
      - Node.js CI
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
#        with:
#          registry-url: 'https://registry.npmjs.org/'
#          node-version-file: '.nvmrc'
#          cache: 'npm'

      - name: Install npm packages
        run: npm install

      - name: Unit tests
        run: npm test

    #  - name: Build Banana
    #    run: npm run banana -- --build --env prod

    #  - uses: actions/upload-artifact@v4
    #    with:
    #      name: banana
    #      path: ./build/

      - name: Publish NPM package
        run: npm publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}