name: Publish Package To NPM

on:  
  workflow_run:
    workflows:
      - Node.js CI
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run:  |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout $CI_COMMIT_REF_NAME
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@tenado"
          SPACE_CHAR=" "
          npx standard-version --releaseCommitMessageFormat "chore(release):${SPACE_CHAR}{{currentTag}}"
          git push --follow-tags origin $CI_COMMIT_REF_NAME
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}